version: "3"

services:
  mongodb:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: e01
      POSTGRES_PASSWORD: 12345

  migration:
    build: ./migration
    image: migration:0.1
    container_name: migration
    environment:
      PSQL_DB_NAME: e01
      PSQL_HOST: postgres
      PSQL_PORT: 5432
      PSQL_USER: postgres
      PSQL_PASSWORD: 12345
      MONGO_HOST: mongo
      MONGO_PORT: 27017
    depends_on:
      - mongodb
      - postgres



