version: "3"

services:
  mongodb:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: e01
      POSTGRES_PASSWORD: 12345

  migration:
    build: ./migration
    image: migration:1.0
    container_name: migration
    environment:
      PSQL_DB_NAME: e01
      PSQL_HOST: postgres
      PSQL_PORT: 5432
      PSQL_USER: postgres
      PSQL_PASSWORD: 12345
      MONGO_HOST: mongo
      MONGO_PORT: 27017
    depends_on:
      - mongodb
      - postgres
  api:
    build: ./api/
    image: api:1.0
    container_name: api
    ports:
      - "8000:8000"
    environment:
      PSQL_DB_NAME: e01
      PSQL_HOST: postgres
      PSQL_PORT: 5432
      PSQL_USER: postgres
      PSQL_PASSWORD: 12345
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      I_AM_GROOT: Pokemon
    env_file:
      - ./.env
    depends_on:
      - mongodb
      - postgres
      - migration




